// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEKGAUJz2RSlhtMfLsUvApyAfWNmTENQ',
    appId: '1:638531777445:web:f90e447c4dc76e0289ee4c',
    messagingSenderId: '638531777445',
    projectId: 'demooo-a0e05',
    authDomain: 'demooo-a0e05.firebaseapp.com',
    storageBucket: 'demooo-a0e05.appspot.com',
    measurementId: 'G-D7TD7WF35L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Vn0EkqPrkBGkwr2tlXj8JAAEb_o7-44',
    appId: '1:638531777445:android:9f6f1e39b35b5d0c89ee4c',
    messagingSenderId: '638531777445',
    projectId: 'demooo-a0e05',
    storageBucket: 'demooo-a0e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtQRKvw1zKrax1Whgh_xPwnV69xmHrts',
    appId: '1:638531777445:ios:ec915c22dade6a1c89ee4c',
    messagingSenderId: '638531777445',
    projectId: 'demooo-a0e05',
    storageBucket: 'demooo-a0e05.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtQRKvw1zKrax1Whgh_xPwnV69xmHrts',
    appId: '1:638531777445:ios:ec915c22dade6a1c89ee4c',
    messagingSenderId: '638531777445',
    projectId: 'demooo-a0e05',
    storageBucket: 'demooo-a0e05.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEKGAUJz2RSlhtMfLsUvApyAfWNmTENQ',
    appId: '1:638531777445:web:8ea0ffdbbbf2a47b89ee4c',
    messagingSenderId: '638531777445',
    projectId: 'demooo-a0e05',
    authDomain: 'demooo-a0e05.firebaseapp.com',
    storageBucket: 'demooo-a0e05.appspot.com',
    measurementId: 'G-96DPSV6F47',
  );
}
